platform :ios, '6.1'

pod 'MBProgressHUD'
pod 'FormatterKit'
pod 'JCNotificationBannerPresenter'
pod 'iToast'
pod 'ALAlertBanner', '~> 0.3.0'
pod 'AFNetworking', '~> 2.1.0'
pod 'PKRevealController', '~> 2.0.5'
pod 'SFHFKeychainUtils'
pod 'couchbase-lite-ios'
pod 'CocoaLumberjack', '~> 1.8.0'
pod 'CocoaAsyncSocket', '~> 7.3.2'
pod 'XMLDictionary', '1.3'